version: 0.2

phases:
  install:
    commands:
      - printenv
      - dotnet tool install --global Amazon.Lambda.Tools --version 3.1.2

  build:
    commands:
      - cd ./src
      - dotnet restore
      - dotnet build

  post_build:
    commands:
        - pwd
        - dotnet lambda package --configuration release --framework netcoreapp2.1 --output-package bin/release/netcoreapp2.1/deploy-package.zip
        - cp ../buildspec-serverless-deploy.yml bin/release/netcoreapp2.1
        - cp ./serverless.yml bin/release/netcoreapp2.1

artifacts:  
  base-directory: ./src/bin/release/netcoreapp2.1/
  files:
    - '**/*'