version: 0.2

phases:
  install:
    commands:
      - printenv
      - npm install
      - npm install -g serverless
      - dotnet tool install --global Amazon.Lambda.Tools --version 3.1.2

  build:
    commands:
      - cd ./src
      - dotnet restore
      - dotnet build

  post_build:
    commands:
        - dotnet lambda package --configuration release --framework netcoreapp2.1 --output-package bin/release/netcoreapp2.1/deploy-package.zip
        - serverless deploy -v