service: realvision-lambdatestapi

provider:
  name: aws
  runtime: dotnetcore2.1
  region: us-east-1

package:
  artifact: ./deploy-package.zip

functions:
  api:
    handler: Realvision.LambdaTestApi::Realvision.LambdaTestApi.LambdaEntryPoint::FunctionHandlerAsync
    events:
     - http:
         path: /{proxy+}
         method: ANY