service: realvision-lambdatestapi

provider:
  name: aws
  runtime: dotnetcore2.1
  region: us-east-1
  #profile: dandonovan-default

package:
  artifact: deploy-package.zip
  #artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  api:
    handler: Realvision.LambdaTestApi::Realvision.LambdaTestApi.LambdaEntryPoint::FunctionHandlerAsync
    events:
     - http:
         path: /{proxy+}
         method: ANY